/**************************************************************************/
/**************************************************************************/
/**********             CASO SUSODA - OLAP - ESTRELLA            **********/
/**************************************************************************/
/**************************************************************************/

CREATE DATABASE SusodaOlapDb;
GO

USE SusodaOlapDb;


CREATE TABLE DIM_PROVEEDOR(
	ID_PROVEEDOR INT IDENTITY(1,1),
	CODIGO INT NOT NULL,
	NOMBRE VARCHAR(50) NOT NULL,
	PROVINCIA VARCHAR(78) NOT NULL,
	CONSTRAINT PK_DIM_PROVEEDOR PRIMARY KEY(ID_PROVEEDOR)
);


CREATE TABLE DIM_INSUMO(
	ID_INSUMO INT IDENTITY(1,1),
	CODIGO INT NOT NULL,
	NOMBRE VARCHAR(50) NOT NULL,
	UNIDAD_MEDIDA VARCHAR(10) NOT NULL,
	CONSTRAINT PK_DIM_INSUMO PRIMARY KEY(ID_INSUMO)
);


CREATE TABLE DIM_TIEMPO(
	ID_TIEMPO INT IDENTITY(1,1),
	FECHA DATE NOT NULL,
	AÑO INT NOT NULL,
	MES_DEL_AÑO INT NOT NULL,
	MES VARCHAR(10) NOT NULL,--Nombre del mes
	DIA_DEL_MES INT NOT NULL,
	DIA VARCHAR(10) NOT NULL,--Nombre del dia
	TRIMESTRE VARCHAR(10) NOT NULL,
	CONSTRAINT PK_DIM_TIEMPO PRIMARY KEY(ID_TIEMPO)
);

CREATE TABLE FACT_COTIZACION(
	ID_PROVEEDOR INT NOT NULL,
	ID_INSUMO INT NOT NULL,
	ID_TIEMPO INT NOT NULL,
	DIAS_VALIDEZ INT NOT NULL,
	PRECIO_UNIT DECIMAL(10,2) NOT NULL,
	CANTIDAD INT NOT NULL,
	SUBTOTAL DECIMAL(10,2) NOT NULL,
	CONSTRAINT PK_FACT_COTIZACION PRIMARY KEY(ID_PROVEEDOR, ID_INSUMO, ID_TIEMPO),
	CONSTRAINT FK_FACT_COTIZACION_DIM_PROVEEDOR FOREIGN KEY(ID_PROVEEDOR)
		REFERENCES DIM_PROVEEDOR(ID_PROVEEDOR),
	CONSTRAINT FK_FACT_COTIZACION_DIM_INSUMO FOREIGN KEY(ID_INSUMO)
		REFERENCES DIM_INSUMO(ID_INSUMO),
	CONSTRAINT FK_FACT_COTIZACION_DIM_TIEMPO FOREIGN KEY(ID_TIEMPO)
		REFERENCES DIM_TIEMPO(ID_TIEMPO)
);