/**************************************************************************/
/**************************************************************************/
/************              CASO SUSODA - OLTP                  ************/
/**************************************************************************/
/**************************************************************************/

CREATE DATABASE SusodaOltpDb;
GO

USE SusodaOltpDb;
GO

CREATE TABLE CLIENTE(
	ID_CLIENTE INT IDENTITY(1,1),
	NOMBRE VARCHAR(50) NOT NULL,
	APELLIDO VARCHAR(50) NOT NULL,
	CALLE VARCHAR(50) NOT NULL,
	NUMERO INT NOT NULL,
	PROVINCIA VARCHAR(65) NOT NULL,
	CONSTRAINT PK_CLIENTE PRIMARY KEY(ID_CLIENTE)
);

CREATE TABLE CLIENTE_TELEFONO(
	ID_CLIENTE INT NOT NULL,
	TELEFONO VARCHAR(30) NOT NULL,
	CONSTRAINT PK_CLIENTE_TELEFONO PRIMARY KEY(ID_CLIENTE, TELEFONO),
	CONSTRAINT FK_CLIENTE_TELEFONO_CLIENTE FOREIGN KEY(ID_CLIENTE)
		REFERENCES CLIENTE(ID_CLIENTE)
);

CREATE TABLE CLIENTE_EMAIL(
	ID_CLIENTE INT NOT NULL,
	EMAIL VARCHAR(60) NOT NULL,
	CONSTRAINT PK_CLIENTE_EMAIL PRIMARY KEY(ID_CLIENTE, EMAIL),
	CONSTRAINT FK_CLIENTE_EMAIL_CLIENTE FOREIGN KEY(ID_CLIENTE)
		REFERENCES CLIENTE(ID_CLIENTE)
);

CREATE TABLE PRODUCTO(
	ID_PRODUCTO INT IDENTITY(1,1),
	NOMBRE VARCHAR(100) NOT NULL,
	PRECIO DECIMAL(10,2) NOT NULL,
	CONSTRAINT PK_PRODUCTO PRIMARY KEY(ID_PRODUCTO)
);

CREATE TABLE PRODUCTO_STOCK(
	ID_PRODUCTO INT NOT NULL,
	FECHA DATETIME NOT NULL,
	CANTIDAD INT NOT NULL,
	CONSTRAINT PK_PRODUCTO_STOCK PRIMARY KEY(ID_PRODUCTO, FECHA),
	CONSTRAINT FK_PRODUCTO_STOCK_PRODUCTO FOREIGN KEY(ID_PRODUCTO)
		REFERENCES PRODUCTO(ID_PRODUCTO)
);

CREATE TABLE FORMA_PAGO(
	ID_FORMA_PAGO INT IDENTITY(1,1),
	DESCRIPCION VARCHAR(30) NOT NULL,
	CONSTRAINT PK_FORMA_PAGO PRIMARY KEY(ID_FORMA_PAGO)
);

CREATE TABLE PEDIDO(	
	ID_PEDIDO BIGINT IDENTITY(1,1),
	ID_CLIENTE INT NOT NULL, 
	ID_FORMA_PAGO INT NOT NULL,
	FECHA_PEDIDO DATETIME NOT NULL,
	FECHA_ENTREGA DATETIME NOT NULL, 
	CONSTRAINT PK_PEDIDO PRIMARY KEY(ID_PEDIDO),
	CONSTRAINT FK_PEDIDO_CLIENTE FOREIGN KEY(ID_CLIENTE)
		REFERENCES CLIENTE(ID_CLIENTE),
	CONSTRAINT FK_PEDIDO_FORMA_PAGO FOREIGN KEY(ID_FORMA_PAGO)
		REFERENCES FORMA_PAGO(ID_FORMA_PAGO)
);

CREATE TABLE PRODUCTO_PEDIDO(
	ID_PEDIDO BIGINT NOT NULL,
	ID_PRODUCTO INT NOT NULL,		
	CANTIDAD INT NOT NULL,
	CONSTRAINT PK_PRODUCTO_PEDIDO PRIMARY KEY(ID_PEDIDO, ID_PRODUCTO),	
	CONSTRAINT FK_PRODUCTO_PEDIDO_PEDIDO FOREIGN KEY(ID_PEDIDO)
		REFERENCES PEDIDO(ID_PEDIDO),
	CONSTRAINT FK_PRODUCTO_PEDIDO_PRODUCTO FOREIGN KEY(ID_PRODUCTO)
		REFERENCES PRODUCTO(ID_PRODUCTO)
);

CREATE TABLE INSUMO(
	ID_INSUMO INT IDENTITY(1,1),
	NOMBRE VARCHAR(100) NOT NULL,
	UNIDAD_MEDIDA VARCHAR(20) NOT NULL,
	CONSTRAINT PK_INSUMO PRIMARY KEY(ID_INSUMO)
);

CREATE TABLE INSUMO_STOCK(
	ID_INSUMO INT NOT NULL,
	FECHA DATETIME NOT NULL,
	CONSTRAINT PK_INSUMO_STOCK PRIMARY KEY(ID_INSUMO, FECHA), 
	CONSTRAINT FK_INSUMO_STOCK_INSUMO FOREIGN KEY(ID_INSUMO)
		REFERENCES INSUMO(ID_INSUMO)
);

CREATE TABLE INSUMO_PRODUCTO(
	ID_INSUMO INT NOT NULL,
	ID_PRODUCTO INT NOT NULL,
	CANTIDAD INT NOT NULL,
	CONSTRAINT PK_INSUMO_PRODUCTO PRIMARY KEY(ID_INSUMO, ID_PRODUCTO),
	CONSTRAINT FK_INSUMO_PRODUCTO_INSUMO FOREIGN KEY(ID_INSUMO)
		REFERENCES INSUMO(ID_INSUMO),
	CONSTRAINT FK_INSUMO_PRODUCTO_PRODUCTO FOREIGN KEY(ID_PRODUCTO)
		REFERENCES PRODUCTO(ID_PRODUCTO)
);

CREATE TABLE PROVEEDOR(
	ID_PROVEEDOR INT IDENTITY(1,1),
	NOMBRE VARCHAR(60) NOT NULL,
	PROVINCIA VARCHAR(65)NOT NULL,
	CALLE VARCHAR(60) NOT NULL,
	NUMERO INT NOT NULL,
	CONSTRAINT PK_PROVEEDOR PRIMARY KEY(ID_PROVEEDOR)
);

CREATE TABLE PROVEEDOR_TELEFONO(
	ID_PROVEEDOR INT NOT NULL, 
	TELEFONO VARCHAR(30) NOT NULL,
	CONSTRAINT PK_PROVEEDOR_TELEFONO PRIMARY KEY(ID_PROVEEDOR, TELEFONO),
	CONSTRAINT FK_PROVEEDOR_TELEFONO_PROVEEDOR FOREIGN KEY(ID_PROVEEDOR)
		REFERENCES PROVEEDOR(ID_PROVEEDOR)
);

CREATE TABLE PROVEEDOR_EMAIL(
	ID_PROVEEDOR INT NOT NULL, 
	EMAIL VARCHAR(60) NOT NULL,
	CONSTRAINT PK_PROVEEDOR_EMAIL PRIMARY KEY(ID_PROVEEDOR, EMAIL),
	CONSTRAINT FK_PROVEEDOR_EMAIL_PROVEEDOR FOREIGN KEY(ID_PROVEEDOR)
		REFERENCES PROVEEDOR(ID_PROVEEDOR)
);

CREATE TABLE PROVEEDOR_INSUMO(
	ID_PROVEEDOR INT NOT NULL,
	ID_INSUMO INT NOT NULL,
	CONSTRAINT PK_PROVEEDOR_INSUMO PRIMARY KEY(ID_PROVEEDOR, ID_INSUMO),
	CONSTRAINT FK_PROVEEDOR_INSUMO_PROVEEDOR FOREIGN KEY(ID_PROVEEDOR)
		REFERENCES PROVEEDOR(ID_PROVEEDOR),
	CONSTRAINT FK_PROVEEDOR_INSUMO_INSUMO FOREIGN KEY(ID_INSUMO)
		REFERENCES INSUMO(ID_INSUMO)
);

CREATE TABLE COTIZACION(
	ID_COTIZACION INT IDENTITY(1,1),
	FECHA_EMISION DATE NOT NULL,
	FECHA_VENCIMIENTO DATE NOT NULL,
	ID_PROVEEDOR INT NOT NULL,
	CONSTRAINT PK_COTIZACION PRIMARY KEY(ID_COTIZACION),
	CONSTRAINT FK_COTIZACION_PROVEEDOR FOREIGN KEY(ID_PROVEEDOR)
		REFERENCES PROVEEDOR(ID_PROVEEDOR)
);

CREATE TABLE ORDEN_COMPRA(
	ID_COMPRA INT IDENTITY(1,1),
	FECHA DATETIME NOT NULL,
	CONSTRAINT PK_ORDEN_COMPRA PRIMARY KEY(ID_COMPRA)
);

CREATE TABLE COMPROBANTE_RECEPCION(
	ID_COMPROBANTE INT IDENTITY(1,1),
	ID_COMPRA INT NOT NULL,
	FECHA_RECEPCION DATETIME NOT NULL,
	CANT_RECIBIDA DATETIME NOT NULL,
	CONSTRAINT PK_COMPROBANTE_RECEPCION PRIMARY KEY(ID_COMPROBANTE),
	CONSTRAINT FK_COMPROBANTE_RECEPCION_COMPRA FOREIGN KEY(ID_COMPRA)
		REFERENCES ORDEN_COMPRA(ID_COMPRA)
);

CREATE TABLE DETALLE_COTIZACION(
	ID_COTIZACION INT NOT NULL,
	ID_INSUMO INT NOT NULL,
	ID_COMPRA INT DEFAULT NULL,
	CANT_COTIZADA INT NOT NULL,	
	PRECIO DECIMAL(10,2) NOT NULL,	
	CONSTRAINT PK_DETALLE_COTIZACION PRIMARY KEY(ID_COTIZACION, ID_INSUMO),
	CONSTRAINT FK_DETALLE_COTIZACION_COTIZACION FOREIGN KEY(ID_COTIZACION)
		REFERENCES COTIZACION(ID_COTIZACION),
	CONSTRAINT FK_DETALLE_COTIZACION_PRODUCTO FOREIGN KEY(ID_INSUMO)
		REFERENCES INSUMO(ID_INSUMO),
	CONSTRAINT FK_DETALLE_COTIZACION_ORDEN_COMPRA FOREIGN KEY(ID_COMPRA)
		REFERENCES ORDEN_COMPRA(ID_COMPRA)
); 

CREATE TABLE SOLICITUD(
	ID_SOLICITUD INT IDENTITY(1,1),
	FECHA_EMISION DATETIME NOT NULL,
	FECHA_VENCIMIENTO DATETIME NOT NULL,
	CONSTRAINT PK_SOLICITUD PRIMARY KEY(ID_SOLICITUD)
);

CREATE TABLE SOLICITUD_INSUMO(
	ID_SOLICITUD INT NOT NULL,
	ID_INSUMO INT NOT NULL,
	CANT_SOLICITADA INT NOT NULL,
	CONSTRAINT PK_SOLICITUD_INSUMO PRIMARY KEY(ID_SOLICITUD, ID_INSUMO),
	CONSTRAINT FK_SOLICITUD_INSUMO_SOLICITUD FOREIGN KEY(ID_SOLICITUD)
		REFERENCES SOLICITUD(ID_SOLICITUD),
	CONSTRAINT FK_SOLICITUD_INSUMO_INSUMO FOREIGN KEY(ID_INSUMO)
		REFERENCES INSUMO(ID_INSUMO)
);

CREATE TABLE COTIZACION_SOLICITUD(
	ID_COTIZACION INT NOT NULL,
	ID_SOLICITUD INT NOT NULL,
	CONSTRAINT PK_COTIZACION_SOLICITUD PRIMARY KEY(ID_COTIZACION, ID_SOLICITUD),
	CONSTRAINT FK_COTIZACION_SOLICITUD_COTIZACION FOREIGN KEY(ID_COTIZACION)
		REFERENCES COTIZACION(ID_COTIZACION),
	CONSTRAINT FK_COTIZACION_SOLICITUD_SOLICITUD FOREIGN KEY(ID_SOLICITUD)
		REFERENCES SOLICITUD(ID_SOLICITUD)
);