USE MY_SHOP;

-- //////////CREACION DE VIEWS\\\\\\\\\\

-- Vista VW_EMPLEADOS_DE_VACACIONES muestra todos aquellos empleados que se encuentran de vacaciones
CREATE OR REPLACE VIEW `VW_EMPLEADOS_DE_VACACIONES` AS(
	SELECT CONCAT(NAMES, ' ', LAST_NAME)AS EMPLEADOS_DE_VACACIONES
	FROM EMPLOYEES
	WHERE ID_STATE = 2
);


-- Vista VW_MONTO_VENDIDO_X_VENDEDOR muestra la sumatoria de las ventas hechas por cada vendedor
CREATE OR REPLACE VIEW `VW_MONTO_VENDIDO_X_VENDEDOR` AS(
	SELECT CONCAT(NAMES,' ',LAST_NAME)AS VENDEDOR, SUM(AMOUNT) MONTO_VENDIDO
	FROM SALES
	JOIN EMPLOYEES
		ON SALES.ID_EMPL = EMPLOYEES.ID_EMPL
	GROUP BY VENDEDOR
	ORDER BY MONTO_VENDIDO ASC
);


-- Vista VW_VENDEDOR_MAS_VENTAS muestra el vendedor con mas ventas realizas.
-- En el caso de que mas de un vendedor posea la misma cantidad de ventas maximas, se mostraran todos aquellos que posean esta cantidad de ventas.
CREATE OR REPLACE VIEW `VW_VENDEDOR_MAS_VENTAS` AS(
	SELECT CONCAT(NAMES,' ',LAST_NAME)AS VENDEDOR, COUNT(*)AS CANT_VENTAS
	FROM SALES
	JOIN EMPLOYEES
		ON SALES.ID_EMPL = EMPLOYEES.ID_EMPL
	GROUP BY VENDEDOR
		HAVING CANT_VENTAS = (SELECT COUNT(*) FROM SALES GROUP BY ID_EMPL ORDER BY COUNT(*)DESC LIMIT 1)
);


-- Vista VW_PRODUCTO_MAS_VENDIDO muestra el producto mas vendido del catalogo.
-- En el caso de que un producto haya sido vendido la misma cantidad de maximas ventas, se mostraran todos aquellos que hyan sido vendidos este numero de veces
CREATE OR REPLACE VIEW `VW_PRODUCTO_MAS_VENDIDO` AS(
	SELECT CONCAT(NAME_TYPE,': ',PRODUCTS_ASSEMBLERS.NAME,' ', PRODUCTS.NAME)AS PRODUCTO , SUM(QUANTITY) CANTIDAD 
	FROM SALES_DESCRIPTION
	JOIN PRODUCTS
		ON SALES_DESCRIPTION.ID_PROD = PRODUCTS.ID_PROD
	JOIN PRODUCTS_ASSEMBLERS
		ON PRODUCTS.ID_ASSEMBLER = PRODUCTS_ASSEMBLERS.ID_ASSEMBLER
	JOIN PRODUCTS_TYPE
		ON PRODUCTS.ID_TYPE = PRODUCTS_TYPE.ID_TYPE
	GROUP BY PRODUCTO
		HAVING CANTIDAD = (SELECT SUM(QUANTITY) FROM SALES_DESCRIPTION GROUP BY ID_PROD ORDER BY SUM(QUANTITY) DESC LIMIT 1)
);


-- Vista VW_TIPOS_PRODUCTOS_X_MARCA muestra la cantidad de tipos de productos que ofrece cada marca en el catalogo de ventas.
CREATE OR REPLACE VIEW `VW_TIPOS_PRODUCTOS_X_MARCA` AS(
	SELECT PRODUCTS_ASSEMBLERS.NAME AS MARCA, NAME_TYPE AS TIPO, COUNT(*)AS CANTIDAD
	FROM PRODUCTS
	JOIN PRODUCTS_ASSEMBLERS
		ON PRODUCTS.ID_ASSEMBLER = PRODUCTS_ASSEMBLERS.ID_ASSEMBLER
	JOIN PRODUCTS_TYPE
		ON PRODUCTS.ID_TYPE = PRODUCTS_TYPE.ID_TYPE
	GROUP BY PRODUCTS_ASSEMBLERS.NAME, NAME_TYPE 
	ORDER BY MARCA ASC
);



-- Llamado a las vistas

SELECT * FROM VW_EMPLEADOS_DE_VACACIONES;
SELECT * FROM VW_MONTO_VENDIDO_X_VENDEDOR;
SELECT * FROM VW_VENDEDOR_MAS_VENTAS;
SELECT * FROM VW_PRODUCTO_MAS_VENDIDO;
SELECT * FROM VW_TIPOS_PRODUCTOS_X_MARCA;