USE MY_SHOP;

-- La funcion FN_BUSCAR_CLIENTE_X_ID devuelve el nombre y apellido (Si es que posee) del cliente segun el ID_CLIENTE ingresado en el parametro de entrada.

DROP FUNCTION IF EXISTS FN_BUSCAR_CLIENTE_X_ID;
DELIMITER $$
CREATE FUNCTION  `FN_BUSCAR_CLIENTE_X_ID` (ID_CLIENTE INT) 
RETURNS VARCHAR (100)
DETERMINISTIC
BEGIN
DECLARE CLIENT VARCHAR(100);
IF ID_CLIENTE IN (SELECT ID_CLIENT FROM CLIENTS) THEN
	IF (SELECT LAST_NAME FROM CLIENTS WHERE ID_CLIENT = ID_CLIENTE) IS NOT NULL THEN
		SET CLIENT = (SELECT CONCAT(NAME, ' ', LAST_NAME) FROM CLIENTS WHERE ID_CLIENT = ID_CLIENTE	);
	ELSE 
		SET CLIENT = (SELECT NAME FROM CLIENTS WHERE ID_CLIENT = ID_CLIENTE);
    END IF;    
ELSE
	SET CLIENT = "The parameter ID_CLIENTE does not exist in the CLIENTS table.";
END IF;
RETURN CLIENT;
END$$
DELIMITER ;



-- La funcion FN_MAX_MIN_PRECIO_TIPO_PRODUCTO devuelve una cadena de caracteres con el detalle del producto con mayor o nenor valor dentro de un tipo seleccionado.
-- Para su funcionamiento la funcion requiere en sus parametros de entrada el ID del tipo de producto y la palabra MAX o MIN segun se requiera.

DROP FUNCTION IF EXISTS FN_MAX_MIN_PRECIO_TIPO_PRODUCTO;
DELIMITER $$
CREATE FUNCTION `FN_MAX_MIN_PRECIO_TIPO_PRODUCTO`(ID_TIPO INT, MAX_MIN VARCHAR(3))
RETURNS VARCHAR(150)
DETERMINISTIC
BEGIN
DECLARE DETAIL VARCHAR (150);
IF MAX_MIN = 'MAX' OR MAX_MIN = 'MIN' THEN
	IF ID_TIPO IN (SELECT ID_TYPE FROM PRODUCTS_TYPE) THEN
		IF MAX_MIN = 'MAX' THEN
			SET DETAIL = (
				SELECT CONCAT(PRODUCTS_TYPE.NAME_TYPE, " ",	PRODUCTS_ASSEMBLERS.NAME," ",PRODUCTS.NAME, ": ",PRICE, "U$s") 
				FROM PRODUCTS
				JOIN PRODUCTS_TYPE
					ON PRODUCTS.ID_TYPE = PRODUCTS_TYPE.ID_TYPE
				JOIN PRODUCTS_ASSEMBLERS
					ON PRODUCTS.ID_ASSEMBLER = PRODUCTS_ASSEMBLERS.ID_ASSEMBLER
				WHERE PRODUCTS.ID_TYPE = ID_TIPO AND PRICE = (SELECT MAX(PRICE)FROM PRODUCTS WHERE ID_TYPE = ID_TIPO)
                LIMIT 1);
		ELSE
			SET DETAIL = (
				SELECT CONCAT(PRODUCTS_TYPE.NAME_TYPE, " ",	PRODUCTS_ASSEMBLERS.NAME," ",PRODUCTS.NAME, ": ",PRICE, "U$s") 
				FROM PRODUCTS
				JOIN PRODUCTS_TYPE
					ON PRODUCTS.ID_TYPE = PRODUCTS_TYPE.ID_TYPE
				JOIN PRODUCTS_ASSEMBLERS
					ON PRODUCTS.ID_ASSEMBLER = PRODUCTS_ASSEMBLERS.ID_ASSEMBLER
				WHERE PRODUCTS.ID_TYPE = ID_TIPO AND PRICE = (SELECT MIN(PRICE)FROM PRODUCTS WHERE ID_TYPE = ID_TIPO)
                LIMIT 1);
		END IF;
	ELSE 
		SET DETAIL = 'The parameter ID_TIPO does not exist in the ID_TYPE table.';
	END IF;
ELSE
	SET DETAIL = 'The parameter "MIN_MAX" is wrong';
END IF;
RETURN DETAIL;
END$$
DELIMITER ;